// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/wepala/langfuse-go/api/core"
	datasetitems "github.com/wepala/langfuse-go/api/datasetitems"
	datasetrunitems "github.com/wepala/langfuse-go/api/datasetrunitems"
	datasets "github.com/wepala/langfuse-go/api/datasets"
	health "github.com/wepala/langfuse-go/api/health"
	ingestion "github.com/wepala/langfuse-go/api/ingestion"
	observations "github.com/wepala/langfuse-go/api/observations"
	projects "github.com/wepala/langfuse-go/api/projects"
	prompts "github.com/wepala/langfuse-go/api/prompts"
	score "github.com/wepala/langfuse-go/api/score"
	sessions "github.com/wepala/langfuse-go/api/sessions"
	trace "github.com/wepala/langfuse-go/api/trace"
	http "net/http"
)

type Client struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header

	Datasetitems    *datasetitems.Client
	Datasetrunitems *datasetrunitems.Client
	Datasets        *datasets.Client
	Health          *health.Client
	Ingestion       *ingestion.Client
	Observations    *observations.Client
	Projects        *projects.Client
	Prompts         *prompts.Client
	Score           *score.Client
	Sessions        *sessions.Client
	Trace           *trace.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:         options.BaseURL,
		httpClient:      options.HTTPClient,
		header:          options.ToHeader(),
		Datasetitems:    datasetitems.NewClient(opts...),
		Datasetrunitems: datasetrunitems.NewClient(opts...),
		Datasets:        datasets.NewClient(opts...),
		Health:          health.NewClient(opts...),
		Ingestion:       ingestion.NewClient(opts...),
		Observations:    observations.NewClient(opts...),
		Projects:        projects.NewClient(opts...),
		Prompts:         prompts.NewClient(opts...),
		Score:           score.NewClient(opts...),
		Sessions:        sessions.NewClient(opts...),
		Trace:           trace.NewClient(opts...),
	}
}
