// This file was auto-generated by Fern from our API Definition.

package api

type CreateDatasetItemRequest struct {
	DatasetName    string       `json:"datasetName"`
	Input          interface{}  `json:"input,omitempty"`
	ExpectedOutput *interface{} `json:"expectedOutput,omitempty"`
	Id             *string      `json:"id,omitempty"`
}
