// This file was auto-generated by Fern from our API Definition.

package api

type CreateDatasetRunItemRequest struct {
	RunName       string `json:"runName"`
	DatasetItemId string `json:"datasetItemId"`
	ObservationId string `json:"observationId"`
}
