// This file was auto-generated by Fern from our API Definition.

package api

type ObservationsGetManyRequest struct {
	Page                *int    `json:"-"`
	Limit               *int    `json:"-"`
	Name                *string `json:"-"`
	UserId              *string `json:"-"`
	Type                *string `json:"-"`
	TraceId             *string `json:"-"`
	ParentObservationId *string `json:"-"`
}
