// This file was auto-generated by Fern from our API Definition.

package api

type CreatePromptRequest struct {
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
	Prompt   string `json:"prompt"`
}

type PromptsGetRequest struct {
	Name    string `json:"-"`
	Version *int   `json:"-"`
}
