// This file was auto-generated by Fern from our API Definition.

package api

type CreateScoreRequest struct {
	Id            *string `json:"id,omitempty"`
	TraceId       string  `json:"traceId"`
	Name          string  `json:"name"`
	Value         float64 `json:"value"`
	ObservationId *string `json:"observationId,omitempty"`
	Comment       *string `json:"comment,omitempty"`
}

type ScoreGetRequest struct {
	Page   *int    `json:"-"`
	Limit  *int    `json:"-"`
	UserId *string `json:"-"`
	Name   *string `json:"-"`
}
