// This file was auto-generated by Fern from our API Definition.

package api

type TraceListRequest struct {
	Page   *int    `json:"-"`
	Limit  *int    `json:"-"`
	UserId *string `json:"-"`
	Name   *string `json:"-"`
	// Only traces that include all of these tags will be returned.
	Tags []*string `json:"-"`
}
